# Generated by Django 3.2.5 on 2021-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbc_article',
            name='image',
            field=models.CharField(max_length=1024, null=True, verbose_name='Image'),
        ),
    ]
