# Generated by Django 3.2.5 on 2021-07-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bbc_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Euronews_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('article', models.TextField(default='-', verbose_name='Article')),
                ('image', models.CharField(max_length=1024, null=True, verbose_name='Image')),
                ('url', models.URLField(verbose_name='Original URL')),
            ],
        ),
    ]
