# Generated by Django 3.2.5 on 2021-07-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_euronews_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BBC_article',
            new_name='Article',
        ),
        migrations.DeleteModel(
            name='Euronews_article',
        ),
    ]
