# Generated by Django 3.2.5 on 2021-07-27 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210725_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 15, 42, 5, 349296), verbose_name='Date created'),
        ),
    ]
